"""
Excel workbook generation for report exports (openpyxl).

One sheet per report section, plus a cover sheet with report metadata.
Values are coerced to Excel-safe types (openpyxl rejects tz-aware
datetimes and UUID objects).
"""

import io
from datetime import datetime, timezone
from typing import List
from uuid import UUID

from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.utils import get_column_letter

from schemas.reports import ReportSection

HEADER_FILL = PatternFill("solid", fgColor="1F4E79")
HEADER_FONT = Font(bold=True, color="FFFFFF", size=11)
HEADER_ALIGNMENT = Alignment(horizontal="center", vertical="center")
THIN_BORDER = Border(bottom=Side(style="thin", color="D9D9D9"))

XLSX_MEDIA_TYPE = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"


def _coerce(value):
    """Make a value writable by openpyxl (no tz-aware datetimes, no UUIDs)."""
    if value is None:
        return ""
    if isinstance(value, UUID):
        return str(value)
    if isinstance(value, datetime):
        if value.tzinfo is not None:
            value = value.replace(tzinfo=None)
        return value.strftime("%Y-%m-%d %H:%M:%S")
    if hasattr(value, "value") and hasattr(type(value), "__str__") and not isinstance(value, str):
        # Enum-like objects -> their string value
        return value.value
    if isinstance(value, (list, dict)):
        return str(value)
    return value


def _sheet_title(title: str) -> str:
    """Excel sheet names are capped at 31 chars and can't contain []:*?/\\."""
    for ch in "[]:*?/\\":
        title = title.replace(ch, "-")
    return title[:31].strip() or "Sheet"


def build_workbook(sections: List[ReportSection], title: str,
                   filters: dict = None, generated_by: str = None) -> bytes:
    """Render report sections into a styled .xlsx workbook, returned as bytes."""
    wb = Workbook()
    generated_at = datetime.now(timezone.utc).replace(tzinfo=None)

    # Cover sheet
    cover = wb.active
    cover.title = "Summary"
    cover.column_dimensions["A"].width = 28
    cover.column_dimensions["B"].width = 60
    cover["A1"] = title
    cover["A1"].font = Font(bold=True, size=14)
    cover["A3"] = "Generated at"
    cover["B3"] = generated_at.strftime("%Y-%m-%d %H:%M:%S")
    cover["A4"] = "Generated by"
    cover["B4"] = generated_by or ""
    row = 6
    if filters:
        for key, value in filters.items():
            if value is not None:
                cover.cell(row=row, column=1, value=str(key).replace("_", " ").title())
                cover.cell(row=row, column=2, value=str(value))
                row += 1
    row += 1
    for section in sections:
        cover.cell(row=row, column=1, value=section.title)
        cover.cell(row=row, column=2, value=f"{len(section.rows)} rows")
        row += 1

    # Data sheets
    for section in sections:
        ws = wb.create_sheet(_sheet_title(section.title))
        # Header row
        for col, name in enumerate(section.columns, start=1):
            cell = ws.cell(row=1, column=col, value=name)
            cell.fill = HEADER_FILL
            cell.font = HEADER_FONT
            cell.alignment = HEADER_ALIGNMENT
        # Data rows
        for r, row_data in enumerate(section.rows, start=2):
            for c, value in enumerate(row_data, start=1):
                ws.cell(row=r, column=c, value=_coerce(value)).border = THIN_BORDER
        # Column widths (capped)
        for col, name in enumerate(section.columns, start=1):
            max_len = len(str(name))
            for row_data in section.rows[:500]:
                if col - 1 < len(row_data):
                    max_len = max(max_len, len(str(_coerce(row_data[col - 1]) or "")))
            ws.column_dimensions[get_column_letter(col)].width = min(max_len + 2, 60)
        # Freeze header + auto-filter
        ws.freeze_panes = "A2"
        if section.rows:
            ws.auto_filter.ref = f"A1:{get_column_letter(len(section.columns))}{len(section.rows) + 1}"

    buffer = io.BytesIO()
    wb.save(buffer)
    return buffer.getvalue()